routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::group(['middleware' => ['install']], function () {
	//Auth Route
	Route::get('/login', function () {
		return redirect('login');
	});

	Auth::routes();
	
	//Frontend Route
	Route::get('/', 'WebsiteController@index');
	Route::get('/post/{slug?}', 'WebsiteController@single');
	Route::get('/category/{id?}', 'WebsiteController@category_archive');
	Route::get('/notice/{id?}', 'WebsiteController@notice');
	Route::get('/event/{id?}', 'WebsiteController@event');
	Route::post('/contact/send_message', 'WebsiteController@send_message');
	Route::get('/site/{slug?}', 'WebsiteController@index');

	
	Route::group(['middleware' => ['auth']], function () {
		/** Common Route for All **/
		Route::get('dashboard','DashboardController@index')->name('dashboard');	
		
		//Profile Controller
		Route::get('profile/my_profile', 'ProfileController@my_profile');
		Route::get('profile/edit', 'ProfileController@edit');
		Route::post('profile/update', 'ProfileController@update');
		Route::get('profile/changepassword', 'ProfileController@change_password');
		Route::post('profile/updatepassword', 'ProfileController@update_password');
			
		
		/** Permission Route Group **/
		Route::group(['middleware' => ['permission']], function () {
		
			//User Controller
			Route::get('users/get_users/{user_type}', 'UserController@get_users');
			Route::resource('users','UserController');

			//FrontOffice Route
			Route::get('frontoffice/{page?}','FrontOfficeController@index')->name('frontoffice.main_screen');
			Route::resource('admission_enquiries','AdmissionEnquiryController');
			Route::resource('visitor_informations','VisitorInformationController');
			Route::resource('phone_call_logs','PhoneCallLogController');
			Route::resource('complains','ComplainController');
			
			//Teacher Route
			Route::get('teachers/excel_import','TeacherController@excel_import')->name('teachers.excel_import');
			Route::post('teachers/excel_store','TeacherController@excel_store')->name('teachers.excel_import');
			Route::resource('teachers','TeacherController');
			
			//Parents Route
			Route::get('parents/get_parents','ParentController@get_parents');
			Route::resource('parents','ParentController');
			
			//Student Route
			Route::get('students/excel_import','StudentController@excel_import')->name('students.excel_import');
			Route::post('students/excel_store','StudentController@excel_store')->name('students.excel_store');
			Route::get('students/id_card/{student_id}', 'StudentController@id_card')->name('students.view_id_card');
			Route::get('students/class/{class_id?}', 'StudentController@class')->name('students.index');
			Route::get('students/get_subjects/{class_id}', 'StudentController@get_subjects');
			Route::get('students/get_students/{class_id}/{section_id}', 'StudentController@get_students');
			Route::match(['get','post'],'students/promote/{step?}','StudentController@promote')->name('students.promote');
			Route::resource('students','StudentController');
			
			//Class Controller
			Route::resource('class','ClassController');
			
			//Section Route
			Route::post('sections/section', 'SectionController@get_section');
			Route::get('sections/class/{class_id}', 'SectionController@index')->name('sections.index');
			Route::resource('sections','SectionController');
			
			//Subject Route
			Route::get('subjects/class/{class_id}', 'SubjectController@index')->name('subjects.index');
			Route::post('subjects/subject', 'SubjectController@get_subject');
			Route::resource('subjects','SubjectController');
			
			//Assign Subject Route
			Route::post('assignsubjects/search', 'AssignSubjectController@search')->name('assignsubjects.index');
			Route::resource('assignsubjects','AssignSubjectController');
			
			Route::resource('syllabus','SyllabusController');
			Route::resource('assignments','AssignmentController');
			Route::resource('academic_years','AcademicYearController');	
			Route::resource('student_groups','StudentGroupController');
			
			//Class Routine
			Route::get('class_routines', 'ClassRoutineController@index')->name('class_routines.index');
			Route::get('class_routines/class/{class_id}', 'ClassRoutineController@class')->name('class_routines.index');
			Route::get('class_routines/manage/{class_id}/{section_id}', 'ClassRoutineController@manage')->name('class_routines.edit');
			Route::post('class_routines/store', 'ClassRoutineController@store')->name('class_routines.create');
			Route::get('class_routines/show/{class_id}/{section_id}', 'ClassRoutineController@show')->name('class_routines.index');
			
			//Attendance Controller
			Route::match(['get','post'],'student/attendance','AttendanceController@student_attendance')->name('student_attendance.create');
			Route::post('student/attendance/save', 'AttendanceController@student_attendance_save')->name('student_attendance.create');
			Route::match(['get','post'],'staff/attendance','AttendanceController@staff_attendance')->name('staff_attendance.create');
			Route::post('staff/attendance/save', 'AttendanceController@staff_attendance_save')->name('staff_attendance.create');
			
			
			//Utility Controller
			Route::match(['get', 'post'],'administration/general_settings/{store?}', 'UtilityController@settings')->name('general_settings.update');
			Route::post('administration/theme_option/{store?}', 'UtilityController@update_theme_option')->name('theme_option.update');
			Route::get('administration/change_session/{session_id}', 'UtilityController@change_session')->name('general_settings.update');
			Route::post('administration/upload_logo', 'UtilityController@upload_logo')->name('general_settings.update');
			Route::get('administration/backup_database', 'UtilityController@backup_database')->name('utility.backup_database');

			//Language Controller
			Route::resource('languages','LanguageController');
			
			//PickList Controller
			Route::get('picklists/type/{type}', 'PicklistController@type')->name('picklists.index');
			Route::resource('picklists','PicklistController');

			//Library Controller
			Route::get('librarymembers/librarycard/{id}', 'LibraryMemberController@library_card')->name('librarymembers.view_library_card');
			Route::post('librarymembers/section', 'LibraryMemberController@get_section');
			Route::post('librarymembers/student', 'LibraryMemberController@get_student');
			Route::resource('librarymembers','LibraryMemberController');

			//Book Controller
			Route::resource('books','BookController');

			//Book Issue  Controller
			Route::match(['get','post'],'bookissues/list/{library_id?}','BookIssueController@index')->name('bookissues.index');
			Route::get('bookissues/return/{id}', 'BookIssueController@book_return')->name('bookissues.return');
			Route::resource('bookissues','BookIssueController');

			//BookCategory Controller
			Route::resource('bookcategories','BookCategoryController');

			//Transport Controller
			Route::resource('transportvehicles','TransportVehicleController');

			//Transport Controller
			Route::resource('transports','TransportController');

			//Transport Member Controller
			Route::post('transportmembers/section', 'TransportMemberController@get_section');
			Route::post('transportmembers/student', 'TransportMemberController@get_student');
			Route::post('transportmembers/transport_fee', 'TransportMemberController@get_transport_fee');
			Route::get('transportmembers/list/{type?}/{class?}', 'TransportMemberController@index')->name('transportmembers.index');
			Route::resource('transportmembers','TransportMemberController');

			//Hostel Controller
			Route::resource('hostels','HostelController');

			//Hostel Category Controller
			Route::resource('hostelcategories','HostelCategoryController');

			//Hostel Member Controller
			Route::get('hostelmembers/class/{class_id}', 'HostelMemberController@index')->name('hostelmembers.index');
			Route::get('hostelmembers/create/{id?}', 'HostelMemberController@create')->name('hostelmembers.create');
			Route::post('hostelmembers/standard', 'HostelMemberController@get_standard');
			Route::post('hostelmembers/hostel_fee', 'HostelMemberController@get_hostel_fee');
			Route::resource('hostelmembers','HostelMemberController');
			
			// Exam Controller
			Route::match(['get', 'post'],'exams/schedule/{type?}', 'ExamController@exam_schedule')->name('exams.view_schedule');
			Route::match(['get', 'post'],'exams/attendance', 'ExamController@exam_attendance')->name('exams.store_exam_attendance');
			Route::post('exams/store_exam_attendance', 'ExamController@store_exam_attendance')->name('exams.store_exam_attendance');
			Route::post('exams/store_schedule', 'ExamController@store_exam_schedule')->name('exams.store_exam_schedule');
			Route::post('exams/get_exam', 'ExamController@get_exam');
			Route::post('exams/get_subject', 'ExamController@get_subject');
			Route::post('exams/get_teacher_subject', 'ExamController@get_teacher_subject');
			Route::resource('exams','ExamController');
			
			
			//Grade Controller
			Route::resource('grades','GradeController');
			
			//Mark Distribution Controller
			Route::resource('mark_distributions','MarkDistributionController');
			
			//Mark Register
			Route::match(['get', 'post'],'marks/rank/{class?}', 'MarkController@student_ranks')->name('marks.view_student_rank');	
			Route::match(['get', 'post'],'marks/create', 'MarkController@create')->name('marks.create');
			Route::post('marks/store','MarkController@store')->name('marks.store');
			Route::match(['get', 'post'],'marks/{class?}', 'MarkController@index')->name('marks.index');

app/Subject.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Subject extends Model
{
    //
}

app/Http/Controllers/SubjectController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;
use App\Subject;

class SubjectController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index( $class='' )
    {
        $subjects = Subject::select('*','subjects.id AS id')
                        ->join('classes','classes.id','=','subjects.class_id')
                        ->where('subjects.class_id', $class)
						->orderBy('subjects.id', 'DESC')
                        ->get();
        return view('backend.subjects.subject-list',compact('subjects','class'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
       return view('backend.subjects.subject-add');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $this->validate($request, [
            'subject_name' => 'required|string|max:191',
            'subject_code' => 'required|string|max:191',
            'subject_type' => 'string',
            'class_id' => 'required',
			'full_mark' => 'integer',
            'pass_mark' => 'integer'
        ]);

        $subject = New Subject();
        $subject->subject_name = $request->subject_name;
        $subject->subject_code = $request->subject_code;
        /*$subject->subject_type = $request->subject_type;*/
        $subject->class_id = $request->class_id;
        /*$subject->full_mark = $request->full_mark;
        $subject->pass_mark = $request->pass_mark;*/
        $subject->save();
        return redirect('subjects/create')->with('success',_lang('Information has been added'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function get_subject(Request $request)
    {
        $results = Subject::where('class_id',$request->class_id)->orderBy('id', 'DESC')->get();
        $subjects = '';
        $subjects .= '<option value="">Select One</option>';
        foreach($results as $data){
            $subjects .= '<option value="'.$data->id.'">'.$data->subject_name.'</option>';
        }
        return $subjects;
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        $subject = Subject::find($id);
        return view('backend.subjects.subject-edit',compact('subject'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        $this->validate($request, [
            'subject_name' => 'required|string|max:191',
            'subject_code' => 'required|string|max:191',
            'subject_type' => 'string',
            'class_id' => 'required',
            'full_mark' => 'integer',
            'pass_mark' => 'integer'
        ]);

        $subject = Subject::find($id);
        $subject->subject_name = $request->subject_name;
        $subject->subject_code = $request->subject_code;
        /*$subject->subject_type = $request->subject_type;*/
        $subject->class_id = $request->class_id;
		/*$subject->full_mark = $request->full_mark;
        $subject->pass_mark = $request->pass_mark;*/
        $subject->save();
        return redirect('subjects')->with('success',_lang('Information has been updated'));
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        $subject = Subject::find($id);
        $subject->delete();
        return redirect('subjects')->with('success',_lang('Information has been deleted'));
    }
}

resources/views/backend/subjects/subject-add.blade.php
@extends('layouts.backend')
@section('content')
<div class="row">
	<div class="col-md-10">
		<div class="panel panel-default" data-collapsed="0">
			<div class="panel-heading">
				<div class="panel-title" >
					{{_lang('Add New Subject')}}
				</div>
			</div>
			<div class="panel-body">
				<form action="{{route('subjects.store')}}" class="validate" autocomplete="off" method="post" accept-charset="utf-8">
					@csrf
					<div class="col-md-6">
						<div class="form-group">
							<label class="control-label">{{_lang('Subject Name')}}</label>
							<input type="text" class="form-control" name="subject_name" value="{{ old('subject_name') }}" placeholder="Ex.: Matemática" required>
						</div>
					</div>
					<div class="col-md-6">
						<div class="form-group">
							<label class="control-label">{{_lang('Subject Code')}}</label>
							<input type="text" class="form-control" name="subject_code" value="{{ old('subject_code') }}" placeholder="Ex.: 0001" required>
						</div>
					</div>
					<!--<div class="col-sm-6">
					    <div class="form-group">
						    <label class="control-label">{{_lang('Subject Type')}}</label>
							<select name="subject_type" class="form-control select2" required>
								<option value="">Select One</option>
								<option value="Theory">Theory</option>
								<option value="Practical">Practical</option>
							</select>
						</div>
					</div>-->
					<div class="col-sm-6">
					   <div class="form-group">
						    <label class="control-label">Turma</label>
							<select name="class_id" class="form-control select2" required>
								<option value="">Selecionar</option>
								{{ create_option('classes','id','class_name',old('class_id')) }}
							</select>
						</div>
					</div>
					
					<!--<div class="col-md-6">
						<div class="form-group">
							<label class="control-label">{{_lang('Full Marks')}}</label>
							<input type="text" class="form-control int-field" name="full_mark" value="{{ old('full_mark') }}" placeholder="Full Mark" required>
						</div>
					</div>
					
					<div class="col-md-6">
						<div class="form-group">
							<label class="control-label">{{_lang('Passing Marks')}}</label>
							<input type="text" class="form-control int-field" name="pass_mark" value="{{ old('pass_mark') }}" placeholder="Pass Mark" required>
						</div>
					</div>-->
					
					<div class="col-md-12">
						<div class="form-group">
							<button type="submit" class="btn btn-primary">{{_lang('Add Subject')}}</button>
						</div>
					</div>
				</form>
			</div>
		</div>
	</div>
</div>
@endsection

resources/views/backend/subjects/subject-edit.blade.php
@extends('layouts.backend')
@section('content')
<div class="row">
	<div class="col-md-10">
		<div class="panel panel-default" data-collapsed="0">
			<div class="panel-heading">
				<div class="panel-title" >
					{{_lang('Edit Subject')}}
				</div>
			</div>
			<div class="panel-body">
				<form action="{{route('subjects.update',$subject->id)}}" class="validate" autocomplete="off" method="post" accept-charset="utf-8">
					@csrf
					{{ method_field('PATCH') }}
					<div class="col-sm-6">
						<div class="form-group">
							<label class="control-label">{{_lang('Subject Name')}}</label>
							<input type="text" class="form-control" name="subject_name" value="{{ $subject->subject_name }}"required>
						</div>
					</div>
					<div class="col-sm-6">
						<div class="form-group">
							<label class="control-label">{{_lang('Subject Code')}}</label>
							<input type="text" class="form-control" name="subject_code" value="{{ $subject->subject_code }}" required>
						</div>
					</div>
					<!--<div class="col-sm-6">
					    <div class="form-group">
						    <label class="control-label">{{_lang('Subject Type')}}</label>
							<select name="subject_type" class="form-control select2" required>
								<option value="">Select One</option>
								<option @if('Theory'==$subject->subject_type) selected @endif value="Theory">Theory</option>
								<option @if('Practical'==$subject->subject_type) selected @endif value="Practical">Practical</option>
							</select>
						</div>
					</div>-->
					<div class="col-sm-6">
					   <div class="form-group">
						    <label class="control-label">Turma</label>
							<select name="class_id" class="form-control select2" required>
								<option value="">Selecionar</option>
								{{ create_option('classes','id','class_name',$subject->class_id) }}
							</select>
						</div>
					</div>
					
					<!--<div class="col-md-6">
						<div class="form-group">
							<label class="control-label">{{_lang('Full Marks')}}</label>
							<input type="text" class="form-control int-field" name="full_mark" value="{{ $subject->full_mark }}" placeholder="Full Mark" required>
						</div>
					</div>
					
					<div class="col-md-6">
						<div class="form-group">
							<label class="control-label">{{_lang('Passing Marks')}}</label>
							<input type="text" class="form-control int-field" name="pass_mark" value="{{ $subject->pass_mark }}" placeholder="Pass Mark" required>
						</div>
					</div>-->
					
					<div class="form-group">
						<div class="col-md-12">
							<button type="submit" class="btn btn-primary">{{_lang('Update Subject')}}</button>
						</div>
					</div>
				</form>
			</div>
		</div>
	</div>
</div>
@endsection

resources/views/backend/subjects/subject-list.blade.php
@extends('layouts.backend')
@section('content')
<div class="row">
	<div class="col-md-12">
		<div class="panel panel-default" data-collapsed="0">
			<div class="panel-heading">
				<span class="panel-title" >
					{{_lang('Subjects List')}}
				</span>
				<select id="class" class="select_class pull-right" onchange="showClass(this);">
				   <option value="">Selecionar Turma</option>
				   {{ create_option('classes','id','class_name',$class) }}
				</select>
				
				<a class="btn btn-primary btn-sm pull-right" data-title="Add Grade" href="{{ url('subjects/create') }}">{{ _lang('Add New Subject') }}</a>
			</div>
			<div class="panel-body no-export">
				<table class="table table-bordered data-table">
					<thead>
						<th>{{ _lang('Subject Name') }}</th>
						<th>{{ _lang('Subject Code') }}</th>
						<th>{{ _lang('Class') }}</th>
						<!--<th>{{ _lang('Full mark') }}</th>
						<th>{{ _lang('Pass mark') }}</th>-->
						<th>{{ _lang('Action') }}</th>
					</thead>
					<tbody>
						@foreach($subjects AS $data)
						<tr>
							<td>{{ $data->subject_name }}</td>
							<td>{{ $data->subject_code }}</td>
							<td>{{ $data->class_name }}</td>
							<!--<td>{{ $data->full_mark }}</td>
							<td>{{ $data->pass_mark }}</td>-->
							<td>
								<form action="{{route('subjects.destroy',$data->id)}}" method="post">
									<a href="{{route('subjects.edit',$data->id)}}" class="btn btn-warning btn-xs"><i class="fa fa-pencil" aria-hidden="true"></i></a>
									{{ method_field('DELETE') }}
									@csrf
									<button type="submit" class="btn btn-danger btn-xs btn-remove"><i class="fa fa-eraser" aria-hidden="true"></i></button>
								</form>
							</td>
						</tr>
						@endforeach
					</tbody>
				</table>
			</div>
		</div>
	</div>
</div>
@endsection

@section('js-script')
<script>
function showClass(elem){
	if($(elem).val() == ""){
		return;
	}
	window.location = "<?php echo url('subjects/class') ?>/"+$(elem).val();
}
</script>
@stop