routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::group(['middleware' => ['install']], function () {
	//Auth Route
	Route::get('/login', function () {
		return redirect('login');
	});

	Auth::routes();
	
	//Frontend Route
	Route::get('/', 'WebsiteController@index');
	Route::get('/post/{slug?}', 'WebsiteController@single');
	Route::get('/category/{id?}', 'WebsiteController@category_archive');
	Route::get('/notice/{id?}', 'WebsiteController@notice');
	Route::get('/event/{id?}', 'WebsiteController@event');
	Route::post('/contact/send_message', 'WebsiteController@send_message');
	Route::get('/site/{slug?}', 'WebsiteController@index');

	
	Route::group(['middleware' => ['auth']], function () {
		/** Common Route for All **/
		Route::get('dashboard','DashboardController@index')->name('dashboard');	
		
		//Profile Controller
		Route::get('profile/my_profile', 'ProfileController@my_profile');
		Route::get('profile/edit', 'ProfileController@edit');
		Route::post('profile/update', 'ProfileController@update');
		Route::get('profile/changepassword', 'ProfileController@change_password');
		Route::post('profile/updatepassword', 'ProfileController@update_password');
			
		
		/** Permission Route Group **/
		Route::group(['middleware' => ['permission']], function () {
		
			//User Controller
			Route::get('users/get_users/{user_type}', 'UserController@get_users');
			Route::resource('users','UserController');

			//FrontOffice Route
			Route::get('frontoffice/{page?}','FrontOfficeController@index')->name('frontoffice.main_screen');
			Route::resource('admission_enquiries','AdmissionEnquiryController');
			Route::resource('visitor_informations','VisitorInformationController');
			Route::resource('phone_call_logs','PhoneCallLogController');
			Route::resource('complains','ComplainController');
			
			//Teacher Route
			Route::get('teachers/excel_import','TeacherController@excel_import')->name('teachers.excel_import');
			Route::post('teachers/excel_store','TeacherController@excel_store')->name('teachers.excel_import');
			Route::resource('teachers','TeacherController');
			
			//Parents Route
			Route::get('parents/get_parents','ParentController@get_parents');
			Route::resource('parents','ParentController');
			
			//Student Route
			Route::get('students/excel_import','StudentController@excel_import')->name('students.excel_import');
			Route::post('students/excel_store','StudentController@excel_store')->name('students.excel_store');
			Route::get('students/id_card/{student_id}', 'StudentController@id_card')->name('students.view_id_card');
			Route::get('students/class/{class_id?}', 'StudentController@class')->name('students.index');
			Route::get('students/get_subjects/{class_id}', 'StudentController@get_subjects');
			Route::get('students/get_students/{class_id}/{section_id}', 'StudentController@get_students');
			Route::match(['get','post'],'students/promote/{step?}','StudentController@promote')->name('students.promote');
			Route::resource('students','StudentController');
			
			//Class Controller
			Route::resource('class','ClassController');
			
			//Section Route
			Route::post('sections/section', 'SectionController@get_section');
			Route::get('sections/class/{class_id}', 'SectionController@index')->name('sections.index');
			Route::resource('sections','SectionController');
			
			//Subject Route
			Route::get('subjects/class/{class_id}', 'SubjectController@index')->name('subjects.index');
			Route::post('subjects/subject', 'SubjectController@get_subject');
			Route::resource('subjects','SubjectController');
			
			//Assign Subject Route
			Route::post('assignsubjects/search', 'AssignSubjectController@search')->name('assignsubjects.index');
			Route::resource('assignsubjects','AssignSubjectController');
			
			Route::resource('syllabus','SyllabusController');
			Route::resource('assignments','AssignmentController');
			Route::resource('academic_years','AcademicYearController');	
			Route::resource('student_groups','StudentGroupController');
			
			//Class Routine
			Route::get('class_routines', 'ClassRoutineController@index')->name('class_routines.index');
			Route::get('class_routines/class/{class_id}', 'ClassRoutineController@class')->name('class_routines.index');
			Route::get('class_routines/manage/{class_id}/{section_id}', 'ClassRoutineController@manage')->name('class_routines.edit');
			Route::post('class_routines/store', 'ClassRoutineController@store')->name('class_routines.create');
			Route::get('class_routines/show/{class_id}/{section_id}', 'ClassRoutineController@show')->name('class_routines.index');
			
			//Attendance Controller
			Route::match(['get','post'],'student/attendance','AttendanceController@student_attendance')->name('student_attendance.create');
			Route::post('student/attendance/save', 'AttendanceController@student_attendance_save')->name('student_attendance.create');
			Route::match(['get','post'],'staff/attendance','AttendanceController@staff_attendance')->name('staff_attendance.create');
			Route::post('staff/attendance/save', 'AttendanceController@staff_attendance_save')->name('staff_attendance.create');
			
			
			//Utility Controller
			Route::match(['get', 'post'],'administration/general_settings/{store?}', 'UtilityController@settings')->name('general_settings.update');
			Route::post('administration/theme_option/{store?}', 'UtilityController@update_theme_option')->name('theme_option.update');
			Route::get('administration/change_session/{session_id}', 'UtilityController@change_session')->name('general_settings.update');
			Route::post('administration/upload_logo', 'UtilityController@upload_logo')->name('general_settings.update');
			Route::get('administration/backup_database', 'UtilityController@backup_database')->name('utility.backup_database');

			//Language Controller
			Route::resource('languages','LanguageController');
			
			//PickList Controller
			Route::get('picklists/type/{type}', 'PicklistController@type')->name('picklists.index');
			Route::resource('picklists','PicklistController');

			//Library Controller
			Route::get('librarymembers/librarycard/{id}', 'LibraryMemberController@library_card')->name('librarymembers.view_library_card');
			Route::post('librarymembers/section', 'LibraryMemberController@get_section');
			Route::post('librarymembers/student', 'LibraryMemberController@get_student');
			Route::resource('librarymembers','LibraryMemberController');

			//Book Controller
			Route::resource('books','BookController');

			//Book Issue  Controller
			Route::match(['get','post'],'bookissues/list/{library_id?}','BookIssueController@index')->name('bookissues.index');
			Route::get('bookissues/return/{id}', 'BookIssueController@book_return')->name('bookissues.return');
			Route::resource('bookissues','BookIssueController');

			//BookCategory Controller
			Route::resource('bookcategories','BookCategoryController');

			//Transport Controller
			Route::resource('transportvehicles','TransportVehicleController');

			//Transport Controller
			Route::resource('transports','TransportController');

			//Transport Member Controller
			Route::post('transportmembers/section', 'TransportMemberController@get_section');
			Route::post('transportmembers/student', 'TransportMemberController@get_student');
			Route::post('transportmembers/transport_fee', 'TransportMemberController@get_transport_fee');
			Route::get('transportmembers/list/{type?}/{class?}', 'TransportMemberController@index')->name('transportmembers.index');
			Route::resource('transportmembers','TransportMemberController');

			//Hostel Controller
			Route::resource('hostels','HostelController');

			//Hostel Category Controller
			Route::resource('hostelcategories','HostelCategoryController');

			//Hostel Member Controller
			Route::get('hostelmembers/class/{class_id}', 'HostelMemberController@index')->name('hostelmembers.index');
			Route::get('hostelmembers/create/{id?}', 'HostelMemberController@create')->name('hostelmembers.create');
			Route::post('hostelmembers/standard', 'HostelMemberController@get_standard');
			Route::post('hostelmembers/hostel_fee', 'HostelMemberController@get_hostel_fee');
			Route::resource('hostelmembers','HostelMemberController');
			
			// Exam Controller
			Route::match(['get', 'post'],'exams/schedule/{type?}', 'ExamController@exam_schedule')->name('exams.view_schedule');
			Route::match(['get', 'post'],'exams/attendance', 'ExamController@exam_attendance')->name('exams.store_exam_attendance');
			Route::post('exams/store_exam_attendance', 'ExamController@store_exam_attendance')->name('exams.store_exam_attendance');
			Route::post('exams/store_schedule', 'ExamController@store_exam_schedule')->name('exams.store_exam_schedule');
			Route::post('exams/get_exam', 'ExamController@get_exam');
			Route::post('exams/get_subject', 'ExamController@get_subject');
			Route::post('exams/get_teacher_subject', 'ExamController@get_teacher_subject');
			Route::resource('exams','ExamController');
			
			
			//Grade Controller
			Route::resource('grades','GradeController');
			
			//Mark Distribution Controller
			Route::resource('mark_distributions','MarkDistributionController');
			
			//Mark Register
			Route::match(['get', 'post'],'marks/rank/{class?}', 'MarkController@student_ranks')->name('marks.view_student_rank');	
			Route::match(['get', 'post'],'marks/create', 'MarkController@create')->name('marks.create');
			Route::post('marks/store','MarkController@store')->name('marks.store');
			Route::match(['get', 'post'],'marks/{class?}', 'MarkController@index')->name('marks.index');

app/Teacher.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Teacher extends Model
{
    //
}

resources/views/backend/teachers/excel_import.blade.php
@extends('layouts.backend')
@section('content')
<div class="row">
	<div class="col-md-6">
		<div class="panel panel-default" data-collapsed="0">
			<div class="panel-heading">
				<div class="panel-title" >
					{{_lang('Import Excel')}}
				</div>
			</div>
			<div class="panel-body">
				<form method="post" action="{{url('teachers/excel_store')}}" enctype="multipart/form-data" class="validate">
					@csrf
					<div class="col-md-12">
						<div class="form-group">
							<label class="control-label">{{ _lang('File') }}</label>						
							<input type="file" class="form-control appsvan-file" name="excel_file" required>
						</div>
					</div>
					<div class="col-md-12">
						<div class="form-group">
							<button type="submit" class="btn btn-primary rect-btn">{{ _lang('Import') }}</button>
						    <a href="{{ asset('excel/teachers_excel.xlsx') }}" class="btn btn-info pull-right rect-btn">{{ _lang('Download Excel File') }}</a>
						</div>
					</div>
				</form>	
			</div>
		</div>
	</div>
</div>
@endsection

resources/views/backend/teachers/teacher-add.blade.php
@extends('layouts.backend')
@section('content')
<div class="row">
	<div class="col-md-12">
		<div class="panel panel-default" data-collapsed="0">
			<div class="panel-heading">
				<div class="panel-title" >
					{{_lang('Add New Teacher')}}
				</div>
			</div>
			<div class="panel-body">
			  <div class="col-md-8">
				<form action="{{route('teachers.store')}}" method="post" autocomplete="off" class="form-horizontal validate">
					@csrf
					<div class="form-group">
						<label class="col-sm-3 control-label">{{_lang('Name')}}</label>
						<div class="col-sm-9">
							<input type="text" class="form-control" name="name" value="{{ old('name') }}" required>
						</div>
					</div>
					<!--<div class="form-group">
						<label class="col-sm-3 control-label">{{_lang('Designation')}}</label>
						<div class="col-sm-9">    
							<select class="form-control select2" name="designation" required>
							   <option value="">{{ _lang('Select One') }}</option>
							  {{ create_option("picklists","value","value",old('designation'),array("type="=>"Designation")) }}	
							</select>
						</div>
					</div>-->
					<div class="form-group">
						<label class="col-sm-3 control-label">{{_lang('Birthday')}}</label>
						<div class="col-sm-9">
							<input type="text" class="form-control datepicker" name="birthday" value="{{ old('birthday') }}" required>
						</div>
					</div>
					<div class="form-group">
						<label class="col-sm-3 control-label">{{_lang('Gender')}}</label>
						<div class="col-sm-9">
							<select name="gender" class="form-control select2" required>
								<option value="">Selecionar</option>
								<option @if(old('gender')=='Male') selected @endif value="Male">Masculino</option>
								<option @if(old('gender')=='Female') selected @endif value="Female">Feminino</option>
							</select>
						</div>
					</div>
					<!--<div class="form-group">
						<label class="col-sm-3 control-label">{{_lang('Religion')}}</label>
						<div class="col-sm-9">
							<select name="religion" class="form-control niceselect wide" required>
								<option value="">{{ _lang('Select One') }}</option>
								{{ create_option("picklists","value","value",old('religion'),array("type="=>"Religion")) }}	
							</select>
						</div>
					</div>-->
					<div class="form-group">
						<label class="col-sm-3 control-label">{{_lang('Phone')}}</label>
						<div class="col-sm-9">
							<input type="text" class="form-control" name="phone" value="{{ old('phone') }}" required>
						</div>
					</div>
					<div class="form-group">
						<label class="col-sm-3 control-label">{{_lang('Address')}}</label>
						<div class="col-sm-9">
							<textarea class="form-control" name="address" required>{{ old('address') }}</textarea>
						</div>
					</div>
					<div class="form-group">
						<label class="col-sm-3 control-label">{{_lang('Joining Date')}}</label>
						<div class="col-sm-9">
							<input type="text" class="form-control datepicker" name="joining_date" value="{{ old('joining_date') }}" required>
						</div>
					</div>

					<hr>
					<div class="page-header">
					  <h4>Detalhes da Conta</h4>
					</div>
					
					<div class="form-group">
						<label class="col-sm-3 control-label">{{_lang('Email')}}</label>
						<div class="col-sm-9">
							<input type="email" class="form-control" name="email" value="{{ old('email') }}" required>
						</div>
					</div>
					<div class="form-group">
						<label class="col-sm-3 control-label">{{_lang('Password')}}</label>
						<div class="col-sm-9">
							<input type="password" class="form-control" name="password" required>
						</div>
					</div>
					<div class="form-group">
						<label class="col-sm-3 control-label">{{_lang('Confirm Password')}}</label>
						<div class="col-sm-9">
							<input type="password" class="form-control" name="password_confirmation" required>
						</div>
					</div>
					
					<div class="form-group">
						<label class="col-sm-3 control-label">{{_lang('Profile Picture')}}</label>
						<div class="col-sm-9">
							<input type="file" class="form-control dropify" name="image" data-allowed-file-extensions="png jpg jpeg PNG JPG JPEG">
						</div>
					</div>
					<div class="form-group">
						<div class="col-sm-offset-3 col-sm-5">
							<button type="submit" class="btn btn-info">Adicionar Professor</button>
						</div>
					</div>
				</form>
			   </div>	
			</div>
		</div>
	</div>
</div>
@endsection

resources/views/backend/teachers/teacher-edit.blade.php
@extends('layouts.backend')
@section('content')
<div class="row">
	<div class="col-md-12">
		<div class="panel panel-default" data-collapsed="0">
			<div class="panel-heading">
				<div class="panel-title" >
					{{_lang('Update Teacher')}}
				</div>
			</div>
			<div class="panel-body">
			  <div class="col-md-8">
				<form action="{{route('teachers.update',$teacher->id)}}" autocomplete="off" class="form-horizontal validate" autocomplete="off" method="post" enctype="multipart/form-data">
					@csrf
					{{ method_field('PATCH') }}
					<div class="form-group">
						<label class="col-sm-3 control-label">{{_lang('Name')}}</label>
						<div class="col-sm-9">
							<input type="text" class="form-control" name="name" value="{{ $teacher->name }}" required>
						</div>
					</div>
					<!--<div class="form-group">
						<label class="col-sm-3 control-label">{{_lang('Designation')}}</label>
						<div class="col-sm-9">
						    <select class="form-control select2" name="designation" required>
							   <option value="">{{ _lang('Select One') }}</option>
							   {{ create_option("picklists","value","value",$teacher->designation,array("type="=>"Designation")) }}	
							</select>
						</div>
					</div>-->
					
					<div class="form-group">
						<label class="col-sm-3 control-label">{{_lang('Birthday')}}</label>
						<div class="col-sm-9">
							<input type="text" class="form-control datepicker" name="birthday" value="{{ $teacher->birthday }}" required>
						</div>
					</div>
					<div class="form-group">
						<label class="col-sm-3 control-label">{{_lang('Gender')}}</label>
						<div class="col-sm-9">
							<select name="gender" class="form-control select2" required>
								<option @if($teacher->gender=='Male') selected @endif value="Male">Masculino</option>
								<option @if($teacher->gender=='Female') selected @endif value="Female">Feminino</option>
							</select>
						</div>
					</div>
					<!--<div class="form-group">
						<label class="col-sm-3 control-label">{{_lang('Religion')}}</label>
						<div class="col-sm-9">
						    <select name="religion" class="form-control niceselect wide" required>
								<option value="">{{ _lang('Select One') }}</option>
								{{ create_option("picklists","value","value",$teacher->religion,array("type="=>"Religion")) }}	
							</select>
						</div>
					</div>-->
					<div class="form-group">
						<label class="col-sm-3 control-label">{{_lang('Phone')}}</label>
						<div class="col-sm-9">
							<input type="text" class="form-control" name="phone" value="{{ $teacher->phone }}" required>
						</div>
					</div>
					<div class="form-group">
						<label class="col-sm-3 control-label">{{_lang('Address')}}</label>
						<div class="col-sm-9">
							<textarea class="form-control" name="address" required>{{ $teacher->address }}</textarea>
						</div>
					</div>
					<div class="form-group">
						<label class="col-sm-3 control-label">{{_lang('Joining Date')}}</label>
						<div class="col-sm-9">
							<input type="text" class="form-control datepicker" name="joining_date" value="{{ $teacher->joining_date }}" required>
						</div>
					</div>
					
					<hr>
					<div class="page-header">
					  <h4>Login Details</h4>
					</div>
					
					<div class="form-group">
						<label class="col-sm-3 control-label">{{_lang('Email')}}</label>
						<div class="col-sm-9">
							<input type="email" class="form-control" name="email" value="{{ $teacher->email }}" required>
						</div>
					</div>
					<div class="form-group">
						<label class="col-sm-3 control-label">{{_lang('Password')}}</label>
						<div class="col-sm-9">
							<input type="password" class="form-control" name="password">
						</div>
					</div>
					<div class="form-group">
						<label class="col-sm-3 control-label">{{_lang('Confirm Password')}}</label>
						<div class="col-sm-9">
							<input type="password" class="form-control" name="password_confirmation">
						</div>
					</div>
					
					<div class="form-group">
						<label class="col-sm-3 control-label">{{_lang('Profile Picture')}}</label>
						<div class="col-sm-9">
							<input type="file" class="form-control dropify" name="image" data-default-file="{{ asset('uploads/images/'.$teacher->image) }}" data-allowed-file-extensions="png jpg jpeg PNG JPG JPEG">
						</div>
					</div>

					<div class="form-group">
						<div class="col-sm-offset-3 col-sm-5">
							<button type="submit" class="btn btn-info">{{_lang('Update Teacher')}}</button>
						</div>
					</div>
				</form>
			   </div>	
			</div>
		</div>
	</div>
</div>
@endsection

resources/views/backend/teachers/teacher-list.blade.php
@extends('layouts.backend')
@section('content')
<div class="row">
	<div class="col-md-12">
		<div class="panel panel-default">
			<div class="panel-heading">
				<span class="panel-title">{{_lang('Teachers List')}}</span>
			
				<a href="{{route('teachers.create')}}" class="btn btn-info btn-sm pull-right" style="margin-left: 10px;">{{_lang('Add New Teacher')}}</a>
				<!--<a href="{{url('teachers/excel_import')}}" class="btn btn-info btn-sm pull-right ajax-modal" data-title="Import Excel">{{_lang('Import Excel')}}</a>-->
			</div>
			<div class="panel-body">
				<table class="table table-bordered data-table">
					<thead>
						<th>{{_lang('Profile')}}</th>
						<th>{{_lang('Name')}}</th>
						<th>{{_lang('Email')}}</th>
						<!--<th>{{_lang('Designation')}}</th>-->
						<th>{{_lang('Action')}}</th>
					</thead>
					<tbody>
						@foreach($teachers AS $data)
						<tr>
							<td><img src="{{ asset('uploads/images/'.$data->image) }}" width="50px" alt=""></td>
							<td>{{$data->name}}</td>
							<td>{{$data->email}}</td>
							<!--<td>{{$data->designation}}</td>-->
							<td>	
								<form action="{{route('teachers.destroy',$data->id)}}" method="post">
									<a href="{{route('teachers.show',$data->id)}}" data-title="{{ _lang('Teacher Profile') }}" class="btn btn-info btn-xs ajax-modal"><i class="fa fa-eye" aria-hidden="true"></i></a>
								    <a href="{{route('teachers.edit',$data->id)}}" class="btn btn-warning btn-xs"><i class="fa fa-pencil" aria-hidden="true"></i></a>
									{{ method_field('DELETE') }}
    								@csrf
    								<button type="submit" class="btn btn-danger btn-xs btn-remove"><i class="fa fa-eraser" aria-hidden="true"></i></button>
								</form>
							</td>
						</tr>
						@endforeach
					</tbody>
				</table>
			</div>
		</div>
	</div>
</div>
@endsection

resources/views/backend/teachers/teacher-view.blade.php
@extends('layouts.backend')
@section('content')
<div class="row">
	<div class="col-sm-10">
		<div class="panel panel-default" data-collapsed="0">
			<div class="panel-heading">
				<div class="panel-title" >
					{{_lang('Teacher Profile')}}
				</div>
			</div>
			<div class="panel-body">
				<table class="table table-striped table-bordered" width="100%">
					<tbody>
						<tr>
							<td style="text-align: center;" colspan="4"><img width="200px" style="border-radius: 7px;" src="{{ asset('uploads/images/'.$teacher->image) }}"></td>
						</tr>
						<tr>
							<td>{{_lang('Name')}}</td>
							<td>{{$teacher->name}}</td>
						</tr>
						<!--<tr>
							<td>{{_lang('Designation')}}</td>
							<td>{{$teacher->designation}}</td>
						</tr>-->
						<tr>
							<td>{{_lang('Date Of Birth')}}</td>
							<td>{{$teacher->birthday}}</td>
						</tr>
						<tr>
							<td>{{_lang('Gender')}}</td>
							<td>{{$teacher->gender}}</td>
						</tr>
						<!--<tr>
							<td>{{_lang('Religion')}}</td>
							<td>{{$teacher->religion}}</td>
						</tr>-->
						<tr>
							<td>{{ _lang('Joining Date') }}</td>
							<td>{{ $teacher->joining_date }}</td>
						</tr>
						<tr>
							<td>{{ _lang('Address') }}</td>
							<td>{{$teacher->address}}</td>
						</tr>
						<tr>
							<td>{{_lang('Phone')}}</td>
							<td>{{$teacher->phone}}</td>
						</tr>
						<tr>
							<td>{{ _lang('Email') }}</td>
							<td>{{ $teacher->email }}</td>
						</tr>
					</tbody>
				</table>
			</div>
		</div>
	</div>
</div>
@endsection